CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    available BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT NOT NULL,
    booker BIGINT NOT NULL,
    start_booking TIMESTAMP WITH TIME ZONE NOT NULL,
    end_booking TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'WAITING',
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booker_user FOREIGN KEY (booker) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_id FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT chk_booking_time CHECK (start_booking::TIMESTAMP < end_booking::TIMESTAMP),
    CONSTRAINT uq_booking_item_booker UNIQUE (item_id, booker, start_booking)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_comment_text_not_empty CHECK (TRIM(text) != '')
);

CREATE INDEX IF NOT EXISTS idx_booking_item ON booking(item_id);
CREATE INDEX IF NOT EXISTS idx_booking_booker ON booking(booker);
CREATE INDEX IF NOT EXISTS idx_comments_item ON comments(item_id);
CREATE INDEX IF NOT EXISTS idx_comments_user ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments(created DESC);